// ES2015 can't destructure default export
// https://github.com/babel/babel/issues/3049


// Auth
export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESSFUL = 'SIGNIN_SUCCESSFUL';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const REFRESH = 'REFRESH';
export const REFRESH_SUCCESSFUL = 'REFRESH_SUCCESSFUL'
export const REFRESH_FAILURE = 'REFRESH_FAILURE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNOUT = 'SIGNOUT';

export const FETCHED_USER_INFO = 'FETCHED_USER_INFO';

// Twitter Accounts

export const REQUEST_TWITTER_ACCOUNTS = 'REQUEST_TWITTER_ACCOUNTS';
export const FETCHED_TWITTER_ACCOUNTS = 'FETCHED_TWITTER_ACCOUNTS';

export const REQUEST_FINISH_TWITTER_LINK = 'REQUEST_FINISH_TWITTER_LINK';
export const FINISHED_TWITTER_LINK = 'FINISHED_TWITTER_LINK';

export const LINK_TWITTER_ACCOUNT_REDIRECT = 'LINK_TWITTER_ACCOUNT_REDIRECT';

export const REQUEST_UNLINK_TWITTER_ACCOUNT = 'REQUEST_UNLINK_TWITTER_ACCOUNT';
export const UNLINKED_TWITTER_ACCOUNT = 'UNLINKED_TWITTER_ACCOUNT';

// Campaigns

export const REQUEST_CAMPAIGNS = 'REQUEST_CAMPAIGNS';
export const FETCHED_CAMPAIGNS = 'FETCHED_CAMPAIGNS';

// Keywords

export const REQUEST_KEYWORDS = 'REQUEST_KEYWORDS';
export const FETCHED_KEYWORDS = 'FETCHED_KEYWORDS';

export const REQUEST_ADD_KEYWORD = 'REQUEST_ADD_KEYWORD';
export const ADD_KEYWORD_SUCCESSFUL = 'ADD_KEYWORD_SUCCESSFUL';
export const ADD_KEYWORD_FAILURE = 'ADD_KEYWORD_FAILURE';

export const REQUEST_DELETE_KEYWORD = 'REQUEST_DELETE_KEYWORD';
export const DELETE_KEYWORD_SUCCESSFUL = 'DELETE_KEYWORD_SUCCESSFUL';
export const DELETE_KEYWORD_FAILURE = 'DELETE_KEYWORD_FAILURE';

// Stats
export const REQUEST_STATS = 'REQUEST_STATS';
export const FETCHED_STATS = 'FETCHED_STATS';
